### ISSUE TITLE
Can we delete this GitHub repository?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-wcseo10#5]
Development of the test suite has not moved beyond the initial template.

We will therefore delete the repository on 2022-05-05 unless if there is a volunteer from the CITE or TEAM Engine community to lead the development of the executable test suite.

**Comment by dstenger** [comment]
However, there are CTL scripts in following directory: https://github.com/opengeospatial/ets-wcseo10/tree/master/src/main/scripts/ctl
It seems that they were migrated from a SVN repository.
